[package]
name = "bevy-in-app"
version = "0.2.0"
authors = ["jinleili"]
edition = "2021"
rust-version = "1.70"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
libc = "*"
raw-window-handle = "0.5"
wgpu = "0.17"
bevy = { version = "0.12.1", features = [
    "bevy_audio",
    "bevy_asset",
    "bevy_sprite",
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_text",
    "bevy_ui",
    "vorbis",
] }
bevy_rapier2d = { version = "0.24.0", features = [
    "enhanced-determinism",
    "serde-serialize",
    "debug-render-2d",
] }
uuid = { version = "1.3.0", features = ["v4"] }
log = "0.4"

[target.'cfg(target_os = "ios")'.dependencies]
core-graphics = "*"
objc = "*"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13"
jni = "0.21"
jni_fn = "0.1"
# 需要保持与 bevy 一致
ndk-sys = "0.4.1+23.1.7779620"
ndk = "0.7.0"
ndk-context = "*"
log-panics = "*"

[profile.dev]
opt-level = 1 # 1 for minimal optimization and good debugging.
